[package]
name = "solution"
version = "0.1.0"
authors = ["Travis Parks <tparks@pinnacle21.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
